---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.56.147
    jenkins-agent-01:
      ansible_host: 62.84.116.229
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
            jenkins-agent-01:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_connection_type: paramiko
    ansible_user: root
