version: '3.3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab'
    restart: always
    hostname: 'gitlab.combined.mgts'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.combined.mgts:4432'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.combined.mgts.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.combined.mgts.key"
        nginx['redirect_http_to_https_port'] = 4432
    ports:
      - '8001:80'
      - '4432:4432'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      - '$GITLAB_HOME/self-signed:/etc/gitlab/ssl'
    shm_size: '256m'
    networks:
      - gitlab_net

  runner:
    image: 'gitlab/gitlab-runner:alpine'
    container_name: 'gitlab-runner'
    restart: always
    volumes:
      - '/data/docker/gitlab/etc/gitlab-runner:/etc/gitlab-runner'
      - '/data/docker/gitlab/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - gitlab
    networks:
      - gitlab_net

networks:
  gitlab_net:
