---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.47.23
    nexus-01:
      ansible_host: 158.160.40.129
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_connection_type: paramiko
    ansible_user: root
